### ISSUE TITLE
渠道服怎么用

### ISSUE THREAD

**Issue by hhbhw** [0x0194/RE2AC#2]
可否教一下如何改针对的包名

**Comment by 0x0194** [comment]
包名发给我就行，你改不了的。

**Comment by hhbhw** [comment]
com.digitalsky.girlsfrontline.cn.huawei

我是直接从/Android/Data下面复制的，我记得这里也是包名，如有错误请指正，谢谢。

**Comment by 0x0194** [comment]
更新了，下载[zygisk_RE2AC_B1.zip](https://github.com/0x0194/RE2AC/releases/download/B/zygisk_RE2AC_B1.zip)试试，不过看你这是华为的渠道服，比较好奇华为手机能装magisk吗？

**Comment by hhbhw** [comment]
我是在LG的手机上装了HMS Core和华为应用市场，这样华为账号就能用了，然后允许关联启动就行了

**Comment by hhbhw** [comment]
需要什么额外手段吗，比如科学上网，清除缓存之类的，我已经安装了但是并没有效果。

**Comment by 0x0194** [comment]
下载终端模拟器打个log看看，先打开游戏，等进入主界面之后打开终端模拟器，输入`su`授予root权限然后输入
`logcat -s RE2AC:V`

**Comment by 0x0194** [comment]
还有看看安装包`lib`目录有没有`arm64-v8a`这个文件夹

**Comment by 0x0194** [comment]
少前新版本把64位删了，试试B2版

**Comment by hhbhw** [comment]
好的，我试试看
前面的指令用了以后终端无响应，安装包lib里面如下
![8566829a-08df-4f21-9d23-7e1a6c1cfddd_Screenshot_20220524-225837](https://user-images.githubusercontent.com/65343696/170076586-021056b7-0cfc-4367-8299-98d22a68f3c2.png)

**Comment by hhbhw** [comment]
重新试过了，还是不行。附：之前用的终端是晨钟的工具箱，应该不会有影响吧

**Comment by 0x0194** [comment]
我的问题，对32位适配出错，换了个依赖库，应该没问题了。

**Comment by hhbhw** [comment]
今天早上试过了进游戏触发了一个大约50M的更新，但是恰逢维护，开服后发现没有效果。重新下游戏和重新装模块均无法再次触发那个更新。根据前人经验50多M的更新包很可能是成功了（猜测）也不排除是官方的补丁。求教。

**Comment by 0x0194** [comment]
打个log看看
```
su
logcat -s RE2AC:V
```
成功加载会有提示的

**Comment by hhbhw** [comment]
![Screenshot_20220527-100812](https://user-images.githubusercontent.com/65343696/170614515-7a4687d6-792e-4a40-b8f0-686f2a2d2400.png)
似乎是加载了，但是游戏内无效

**Comment by 0x0194** [comment]
你这是模块没加载，加载成功应该是这样。先打开log，然后进游戏，最后看log，还没有提示的话我也搞不懂了
![1](https://user-images.githubusercontent.com/87634467/170626227-d4cf17c4-48cb-4e26-bcf3-fadba16bfa19.png)

**Comment by hhbhw** [comment]
我试着重装了模块也还是没有beginning of crash 那一行，是否需要什么前置模块之类的，有个猜测是不是在换库的时候把我这个华为服的包名换没了（因为不懂所以瞎猜，错了请谅解）

**Comment by hhbhw** [comment]
以及还有个办法可以让您自己测试用，虽然比较麻烦您。您可以自己通过华为官网下载华为应用市场并且从中下载HMS Core.鉴于少前在华为应用市场已经下架，此处给您一个nga论坛的链接可以下载。这个方法对所有安卓机型包括模拟器是通用的。
https://bbs.nga.cn/read.php?tid=29200671&rand=306
麻烦了。

**Comment by 0x0194** [comment]
我是已经用华为服测试过了才问你的。我又加了一些debug信息，你下载b5版本试试

**Comment by hhbhw** [comment]
![Screenshot_20220531-130331](https://user-images.githubusercontent.com/65343696/171096589-e5c333c7-9c75-40f1-b086-2b873b966748.png)
![Screenshot_20220531-130313](https://user-images.githubusercontent.com/65343696/171096626-f7dc4783-8e79-44ea-b0e8-f04c79bbc930.png)
我去，成了…给大佬磕头了。…太厉害了…
