### ISSUE TITLE
3.0大版本更新后游戏会卡在开始解析用户信息

### ISSUE THREAD

**Issue by hhbhw** [0x0194/RE2AC#4]
重装过游戏应该不是游戏问题，附上log
![Screenshot_20220826-140414](https://user-images.githubusercontent.com/65343696/186834258-ed8b013a-be77-42b3-85db-38a700da6a85.png)
![Screenshot_20220826-140754](https://user-images.githubusercontent.com/65343696/186834315-4c124e6b-0301-4413-9741-d3c694c5fded.png)

**Comment by whitespacename** [comment]
不好意思久等了，之前的Github账号邮箱无了没法登陆。我检查了一下代码，是我附加的功能出问题了，模块其实有一个图鉴语音全开的功能，现在去掉之后正常了。

如果你还需要模块的话，这里是新地址
https://github.com/whitespacename/RE2AC

**Comment by hhbhw** [comment]
> 不好意思久等了，之前的Github账号邮箱无了没法登陆。我检查了一下代码，是我附加的功能出问题了，模块其实有一个图鉴语音全开的功能，现在去掉之后正常了。
> 
> 如果你还需要模块的话，这里是新地址 https://github.com/whitespacename/RE2AC

谢谢大佬
